### ISSUE TITLE
example reports a bug

### ISSUE THREAD

**Issue by runnytone** [jihuilee/VCERGM#2]
> # Cross-sectional ERGMs and ad hoc 2-step procedure
> ergmest = cross_sectional_ergm(object = object, network = networks, attr = attr, directed = directed,
+                      degree.spline = degree.spline, interior.knot = interior.knot)
Error in ergm.getnetwork(formula) : 
  The network in the formula 'nets ~ triangle + kstar(2) + nodematch("attr1")' cannot be found.The network in the formula '<environment: 0x1bc159438>' cannot be found.

**Comment by jihuilee** [comment]
Sorry for late response. Please see the latest version of the package & example code and let me know if the problem persists. Thank you so much!
